// This file is auto-generated by @hey-api/openapi-ts

export type Body_contracts_create_contract = {
    contract_in: ContractCreate;
    file?: ((Blob | File) | null);
};

export type Body_contracts_create_invoice = {
    invoice_in: InvoiceCreate;
    file?: ((Blob | File) | null);
};

export type Body_contracts_update_contract = {
    contract_in: ContractUpdate;
    file?: ((Blob | File) | null);
};

export type Body_contracts_update_invoice = {
    invoice_in: InvoiceUpdate;
    file?: ((Blob | File) | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ContractCreate = {
    contract_number?: (string | null);
    contract_name?: (string | null);
    amount?: (number | null);
    sign_date?: (string | null);
    effective_date?: (string | null);
    expiry_date?: (string | null);
    project_id: string;
};

export type ContractProjectCreate = {
    name: string;
    code: string;
    description?: (string | null);
};

export type ContractProjectPublic = {
    name: string;
    code: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ContractProjectsPublic = {
    data: Array<ContractProjectPublic>;
    count: number;
};

export type ContractProjectUpdate = {
    name?: (string | null);
    code?: (string | null);
    description?: (string | null);
};

export type ContractPublic = {
    contract_number?: (string | null);
    contract_name?: (string | null);
    amount?: (number | null);
    sign_date?: (string | null);
    effective_date?: (string | null);
    expiry_date?: (string | null);
    id: string;
    project_id: string;
    file_path?: (string | null);
    parsed_data?: ({
    [key: string]: unknown;
} | null);
    created_at?: (string | null);
};

export type ContractsPublic = {
    data: Array<ContractPublic>;
    count: number;
};

export type ContractUpdate = {
    contract_number?: (string | null);
    contract_name?: (string | null);
    amount?: (number | null);
    sign_date?: (string | null);
    effective_date?: (string | null);
    expiry_date?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InvoiceCreate = {
    invoice_number: string;
    invoice_code: string;
    amount: number;
    invoice_date?: (string | null);
    seller?: (string | null);
    buyer?: (string | null);
    tax_amount?: (number | null);
    remark?: (string | null);
    contract_id: string;
};

export type InvoicePublic = {
    invoice_number: string;
    invoice_code: string;
    amount: number;
    invoice_date?: (string | null);
    seller?: (string | null);
    buyer?: (string | null);
    tax_amount?: (number | null);
    remark?: (string | null);
    id: string;
    contract_id: string;
    file_path?: (string | null);
    parsed_data?: ({
    [key: string]: unknown;
} | null);
    created_at?: (string | null);
};

export type InvoicesPublic = {
    data: Array<InvoicePublic>;
    count: number;
};

export type InvoiceUpdate = {
    invoice_number?: (string | null);
    invoice_code?: (string | null);
    amount?: (number | null);
    invoice_date?: (string | null);
    seller?: (string | null);
    buyer?: (string | null);
    tax_amount?: (number | null);
    remark?: (string | null);
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ContractsReadContractProjectsData = {
    limit?: number;
    skip?: number;
};

export type ContractsReadContractProjectsResponse = (ContractProjectsPublic);

export type ContractsCreateContractProjectData = {
    requestBody: ContractProjectCreate;
};

export type ContractsCreateContractProjectResponse = (ContractProjectPublic);

export type ContractsReadContractProjectData = {
    id: string;
};

export type ContractsReadContractProjectResponse = (ContractProjectPublic);

export type ContractsUpdateContractProjectData = {
    id: string;
    requestBody: ContractProjectUpdate;
};

export type ContractsUpdateContractProjectResponse = (ContractProjectPublic);

export type ContractsDeleteContractProjectData = {
    id: string;
};

export type ContractsDeleteContractProjectResponse = (Message);

export type ContractsReadContractsByProjectData = {
    limit?: number;
    projectId: string;
    skip?: number;
};

export type ContractsReadContractsByProjectResponse = (ContractsPublic);

export type ContractsReadContractData = {
    id: string;
};

export type ContractsReadContractResponse = (ContractPublic);

export type ContractsUpdateContractData = {
    formData: Body_contracts_update_contract;
    id: string;
};

export type ContractsUpdateContractResponse = (ContractPublic);

export type ContractsDeleteContractData = {
    id: string;
};

export type ContractsDeleteContractResponse = (Message);

export type ContractsCreateContractData = {
    formData: Body_contracts_create_contract;
};

export type ContractsCreateContractResponse = (ContractPublic);

export type ContractsReadInvoicesByContractData = {
    contractId: string;
    limit?: number;
    skip?: number;
};

export type ContractsReadInvoicesByContractResponse = (InvoicesPublic);

export type ContractsReadInvoiceData = {
    id: string;
};

export type ContractsReadInvoiceResponse = (InvoicePublic);

export type ContractsUpdateInvoiceData = {
    formData: Body_contracts_update_invoice;
    id: string;
};

export type ContractsUpdateInvoiceResponse = (InvoicePublic);

export type ContractsDeleteInvoiceData = {
    id: string;
};

export type ContractsDeleteInvoiceResponse = (Message);

export type ContractsCreateInvoiceData = {
    formData: Body_contracts_create_invoice;
};

export type ContractsCreateInvoiceResponse = (InvoicePublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);
