"""add contract approval feature

Revision ID: 87f124d90f32
Revises: fe56fa70289e
Create Date: 2026-02-04 12:14:26.091281

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87f124d90f32'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractproject',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('invoice_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('seller', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('buyer', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contract', sa.Column('contract_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('contract', sa.Column('contract_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('contract', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('contract', sa.Column('sign_date', sa.DateTime(), nullable=True))
    op.add_column('contract', sa.Column('effective_date', sa.DateTime(), nullable=True))
    op.add_column('contract', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    op.add_column('contract', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contract', sa.Column('parsed_data', sa.JSON(), nullable=True))
    op.alter_column('contract', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'contract', 'contractproject', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('contract', 'file_type')
    op.drop_column('contract', 'filename')
    op.drop_column('contract', 'parsed')
    op.drop_column('contract', 'uploaded_at')
    op.drop_column('contract', 'original_filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('original_filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('contract', sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('contract', sa.Column('parsed', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('contract', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('contract', sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.alter_column('contract', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('contract', 'parsed_data')
    op.drop_column('contract', 'created_at')
    op.drop_column('contract', 'expiry_date')
    op.drop_column('contract', 'effective_date')
    op.drop_column('contract', 'sign_date')
    op.drop_column('contract', 'amount')
    op.drop_column('contract', 'contract_name')
    op.drop_column('contract', 'contract_number')
    op.drop_table('invoice')
    op.drop_table('contractproject')
    # ### end Alembic commands ###
